# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
export PATH=$PATH:/usr/sbin/:/sbin/:/opt/puppet/sbin/:/opt/puppet/bin:/vagrant/bin
